### ISSUE TITLE
Account is activated more than once

### ISSUE THREAD

**Issue by Omarabdul3ziz** [threefoldtech/tfchain_activation_service#11]
Is it supposed to be only one-time activation with a fund of 1 TFT !?

If you click the button rapidly more than once, the account will be activated more than once and fund with a lot of TFTs 

 

![Screenshot from 2021-10-28 13-05-08](https://user-images.githubusercontent.com/32527347/139243946-a04a279d-5481-4aca-8e84-7b7e4b6de85b.png)

* Using TF Chain Test net
* Activation from [here](https://tfchain.test.threefold.io/activation/)

**Comment by DylanVerstraete** [comment]
fixed
