### ISSUE TITLE
The production docker image uses dev dependencies

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldtech/tfchain_activation_service#20]
The command in the docker image executes the `start` script which requires `nodemon` and `pino-pretty` which are both dev dependencies

**Comment by robvanmieghem** [comment]
`nodemon` does not seems needed to me as it is meant to reload changes in the code in the fly

**Comment by DylanVerstraete** [comment]
Maybe it should not do that, we can have a seperate command to start in production

**Comment by DylanVerstraete** [comment]
https://github.com/threefoldtech/tfchain_activation_service/pull/22

**Comment by robvanmieghem** [comment]
4954a5cb49450550812141349fcb7f74174cf993
